export const DesignData = [
  {
    id: 1,
    title: "Prettyform",
    design: "/design/prettyform.png",
    link: "https://www.figma.com/file/sr5nIapkbxLl5v8JH8yfvi/Website?node-id=6%3A3&t=DVJtTkikOWc6GkKc-1",
    tool: "Figma",
  },
  {
    id: 2,
    title: "Cretten",
    design: "/design/cretten.png",
    link: "https://www.figma.com/file/glBt0DnWZEYBvO6VtGcPoF/Plataforma?node-id=8%3A11&t=Ugm8gSm3nCIxtfNE-1",
    tool: "Figma",
  },
  {
    id: 3,
    title: "Cretten",
    design: "/design/cretten2.png",
    link: "https://www.figma.com/file/glBt0DnWZEYBvO6VtGcPoF/Plataforma?node-id=8%3A11&t=Ugm8gSm3nCIxtfNE-1",
    tool: "Figma",
  },
  {
    id: 4,
    title: "Trading",
    design: "/design/trading.png",
    link: "https://www.figma.com/file/apfy8cHOmetkMtoIx3dGRJ/Trading?node-id=1%3A2&t=5k90GwWjgGJ1TFVV-1",
    tool: "Figma",
  },
  {
    id: 5,
    title: "Emprise Soft",
    design: "/design/soft.png",
    link: "https://www.figma.com/file/VXejk3ciaoR4C04dviIU3l/Nuestra-empresa?node-id=2%3A2&t=Kfg1M0cFfVuxgBPK-1",
    tool: "Figma",
  },
  {
    id: 6,
    title: "Nutrition",
    design: "/design/nutrition.png",
    link: "https://www.figma.com/file/5VhtAq9zEjRBsHGA13gKR2/MARIA-FERNANDA-TORO?node-id=0%3A1&t=7ZoW5LYIrG0mK9wv-1",
    tool: "Figma",
  },
  {
    id: 7,
    title: "Vibra Accesorios",
    design: "/design/vibra.png",
    link: "https://www.figma.com/file/RkJUN0g6QTjOCNRVZwTcmM/Client-Accesorios?node-id=101%3A2&t=xoOMkJr4X7Exy1lh-1",
    tool: "Figma",
  },
];
