import Head from "next/head";
import Link from "next/link";

type Props = {
	theme: boolean;
};

export default function Custom404({ theme }: Props) {
	return (
		<>
			<Head>
				<title>Page Not Found - 404</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<div
				className={`${
					theme
						? "w-full h-full overflow-auto bg-gradient-to-b from-white to-[#f1f7fd] rounded-md duration-200"
						: "w-full h-full overflow-auto bg-gradient-to-b from-[#121314] to-transparent rounded-md duration-200"
				}`}>
				<div
					className={`${
						theme
							? "w-full h-full rounded-t-md flex items-center justify-center"
							: "w-full h-full rounded-t-md flex items-center justify-center"
					}`}>
					<div className="flex flex-col gap-3 items-center">
						<h1 className="text-7xl">Ups! ERROR</h1>
						<p className="font-mono text-2xl">Page not found</p>
						<div className="inline-flex mt-5">
							<Link
								href="/"
								className={`${
									theme
										? "duration-200 bg-black/90 hover:bg-white hover:text-black border border-white hover:border hover:border-black text-white font-bold py-2 px-4 rounded"
										: "duration-200 bg-white hover:bg-black/10 hover:text-white border border-black hover:border hover:border-white text-black font-bold py-2 px-4 rounded"
								}`}>
								Return
							</Link>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}
