import { InterfaceThemeLanguage } from "@/interfaces/Interface";
import Head from "next/head";
import Link from "next/link";

export default function Custom404({
  theme,
  setTheme,
  lang,
  setLang,
}: InterfaceThemeLanguage) {
  return (
    <>
      <Head>
        <title>
          {lang ? "Page Not Found - 404" : "Pagina no encontrada - 404"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div
        className={`${
          theme
            ? "w-full h-full overflow-auto bg-gradient-to-b from-white to-[#f1f7fd] rounded-md duration-200"
            : "w-full h-full overflow-auto bg-transparent rounded-md duration-200"
        }`}
      >
        <div
          className={`${
            theme
              ? "w-full h-full rounded-t-md flex items-center justify-center"
              : "w-full h-full rounded-t-md flex items-center justify-center"
          }`}
        >
          <div className="flex flex-col gap-3 items-center">
            <h1 className="text-6xl font-bold uppercase text-center">
              Error 404
            </h1>
            <p className="font-sans text-2xl">
              {lang ? "Page not found" : "Pagina no encontrada"}
            </p>
            <div className="inline-flex mt-5">
              <Link
                href="/"
                className={`${
                  theme
                    ? "duration-200 bg-black/80 text-white hover:bg-black hover:scale-105 font-bold py-2 px-4 rounded"
                    : "duration-200 bg-white/80 text-black hover:bg-white hover:scale-105 font-bold py-2 px-4 rounded"
                }`}
              >
                {lang ? "Home" : "Inicio"}
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
