import { Lexend } from "@next/font/google";
import Head from "next/head";
import Footer from "@/components/Footer";
import { InterfaceThemeLanguage } from "@/interfaces/Interface";
import { DesignData } from "@/utils/designs";
import Image from "next/image";

const lexend = Lexend({ subsets: ["latin"], weight: "800" });

export default function Design({
  theme,
  setTheme,
  lang,
  setLang,
}: InterfaceThemeLanguage) {
  return (
    <>
      <Head>
        <title>
          {lang ? "Projects - Portfolio" : "Proyectos - Portafolio"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div
        className={`${
          theme
            ? "w-full h-full flex flex-col justify-between overflow-auto bg-gradient-to-b from-white to-transparent rounded-md backdrop-blur-3xl"
            : "w-full h-full flex flex-col justify-between overflow-auto bg-transparent rounded-md backdrop-blur-3xl"
        }`}
      >
        <div>
          <div className="w-full py-5 px-3 flex flex-col  gap-5">
            <h1
              className={lexend.className}
              style={{ fontSize: 50, fontWeight: 800, lineHeight: 1 }}
            >
              {lang ? "Designs" : "Diseños"}
            </h1>
            <p className="text-xl font-sans">
              {lang
                ? "A list of designs I have been working on or built"
                : "Una lista de diseños en los que he estado trabajando o que he construido"}
            </p>
          </div>

          <div className="w-full py-5 pl-3 pr-5 pt-0 grid grid-cols-1 gap-4">
            {DesignData.map(({ id, title, design, tool, link }) => (
              <div
                key={id}
                className={`${
                  theme
                    ? "relative w-full rounded-md flex flex-col justify-between gap-3 hover:border-black/20"
                    : "relative w-full rounded-md flex flex-col justify-between gap-3 hover:border-white/30"
                }`}
              >
                <div className="flex justify-between items-center z-20">
                  <a href={link} rel="noreferrer" target="_blank"></a>
                </div>
                <div className="flex flex-col justify-between gap-5">
                  <div className="w-full flex flex-col">
                    <h1 className="text-3xl font-semibold">{title}</h1>
                  </div>
                  <div className="w-full">
                    <a href={link} rel="noreferrer" target="_blank">
                      <Image
                        className="rounded-md"
                        src={design}
                        width={2000}
                        height={2000}
                        priority
                        alt={title}
                      />
                    </a>
                  </div>
                </div>

                <div className="flex justify-between items-center">
                  <p className="font-semibold flex gap-3">{tool}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <Footer
          theme={theme}
          setTheme={setTheme}
          lang={lang}
          setLang={setLang}
        />
      </div>
    </>
  );
}
