import { Lexend } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import React from "react";

import {
  FaReact,
  FaNodeJs,
  FaHtml5,
  FaCss3Alt,
  FaGitAlt,
  FaGithub,
} from "react-icons/fa";
import { TbBrandNextjs } from "react-icons/tb";
import {
  SiJavascript,
  SiTypescript,
  SiMongodb,
  SiMysql,
  SiTailwindcss,
  SiBitbucket,
  SiJirasoftware,
} from "react-icons/si";
import { InterfaceThemeLanguage } from "@/interfaces/Interface";
import Footer from "@/components/Footer";

const lexend = Lexend({ subsets: ["latin"], weight: "800" });
import { ExperiencesData } from "@/utils/experiences";

export default function Experience({
  theme,
  setTheme,
  lang,
  setLang,
}: InterfaceThemeLanguage) {
  return (
    <>
      <Head>
        <title>
          {lang ? "Experience - Portfolio" : "Experiencia - Portafolio"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div
        className={`${
          theme
            ? "w-full h-full overflow-auto overflow-x-hidden bg-gradient-to-b from-white to-transparent rounded-md"
            : "w-full h-full overflow-auto overflow-x-hidden bg-transparent rounded-md"
        }`}
      >
        <div className="w-full py-5 px-3 flex flex-wrap gap-10">
          <div
            className={`${
              theme ? "flex flex-col gap-5" : "flex flex-col gap-5"
            }`}
          >
            <h1
              className={lexend.className}
              style={{ fontSize: 38, fontWeight: 800, lineHeight: 1 }}
            >
              {lang
                ? "My extensive experience as UI/UX Developer and Designer"
                : "Mi gran experiencia como Desarrollador y Diseñador UI/UX"}
            </h1>

            <p className="text-xl font-sans">
              {lang
                ? "Expert in web development and user experience design, with more than 2 years of experience in creating attractive and efficient websites and applications, using the latest technologies and methodologies in design and development."
                : "Experto en desarrollo web y diseño de experiencia de usuario, con más de 2 años de experiencia en la creación de sitios web y aplicaciones atractivas y eficientes, utilizando las últimas tecnologías y metodologías en diseño y desarrollo."}
            </p>
          </div>

          <div className="w-full flex justify-center items-center">
            <div className="w-1/4 h-full md:flex flex-col justify-between items-center relative pt-2 pr-5 hidden">
              <span
                className={`${
                  theme
                    ? "w-0.5 h-full bg-gradient-to-b from-transparent via-black to-transparent  rounded-full absolute"
                    : " w-0.5 h-full bg-gradient-to-b from-transparent via-white to-transparent  rounded-full absolute"
                }`}
              ></span>
              {ExperiencesData.map(({ id }) => (
                <span
                  key={id}
                  className={`${
                    theme
                      ? "w-3 h-3 bg-black rounded-full duration-200 hover:scale-150"
                      : " w-3 h-3 bg-white rounded-full"
                  }`}
                ></span>
              ))}
            </div>
            <div className="flex flex-wrap gap-10">
              {ExperiencesData.map(
                (
                  {
                    puest,
                    emprise,
                    country,
                    dateInitial,
                    dateFinish,
                    description,
                    descriptionE,
                    tech,
                  },
                  index
                ) => (
                  <div
                    key={index}
                    className={`${theme ? "relative px-1" : "relative px-1"}`}
                  >
                    <div
                      className={`${
                        dateFinish
                          ? "absolute w-10 h-10 left-0 rounded-full animate-bg3 bg-amber-200/50 blur-3xl"
                          : "absolute w-10 h-10 left-0 rounded-full animate-bg3 blur-3xl"
                      }`}
                    ></div>
                    <div className="w-full flex flex-col gap-3">
                      <h1 className="text-3xl font-black">{puest}</h1>
                      <div className="flex flex-col gap-1">
                        <b className="text-xl">{emprise}</b>
                        <p>
                          {country} | {dateInitial} -{" "}
                          {dateFinish ? dateFinish : "Actualmente"}
                        </p>
                      </div>
                      <p
                        className={`${
                          theme
                            ? "font-sans text-lg text-black/60"
                            : "font-sans text-lg text-white/50"
                        }`}
                      >
                        {lang ? descriptionE : description}
                      </p>
                      <div className="flex flex-col gap-1">
                        <h1 className="text-xl font-black">
                          {lang ? "Technologies" : "Tecnologias"}
                        </h1>
                        <div className="pt-2">
                          <div>
                            <div className="flex flex-wrap gap-2">
                              {tech?.map(({ technology }, index) => (
                                <div
                                  key={index}
                                  className={`${
                                    theme
                                      ? " bg-white/20 border border-black/30 text-black/80 py-1 px-2 rounded-md cursor-pointer hover:border hover:border-black/70"
                                      : " bg-black/20 border border-white/30 text-white py-1 px-2 rounded-md cursor-pointer hover:border hover:border-white/100"
                                  }`}
                                >
                                  {technology}
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )
              )}
            </div>
          </div>
          <div>
            <h1
              className={lexend.className}
              style={{ fontSize: 25, fontWeight: 800, lineHeight: 1.2 }}
            >
              {lang
                ? "Some of the great technologies I have knowledge and experience with"
                : "Algunas de las grandes tecnologias que tengo conocimientos y experiencia"}
            </h1>
          </div>
          <div className="flex flex-wrap gap-4 text-4xl">
            <FaReact className="cursor-pointer hover:text-blue-300" />
            <TbBrandNextjs className="cursor-pointer hover:text-slate-300" />
            <SiJavascript className="cursor-pointer hover:text-yellow-400" />
            <SiTypescript className="cursor-pointer hover:text-blue-500" />
            <FaNodeJs className="cursor-pointer hover:text-green-500" />
            <FaHtml5 className="cursor-pointer hover:text-orange-400" />
            <FaCss3Alt className="cursor-pointer hover:text-blue-300" />
            <SiTailwindcss className="cursor-pointer hover:text-blue-300" />
            <SiMongodb className="cursor-pointer hover:text-green-500" />
            <SiMysql className="cursor-pointer hover:text-blue-300" />
            <FaGitAlt className="cursor-pointer hover:text-orange-400" />
            <FaGithub className="cursor-pointer hover:text-slate-300" />
            <SiBitbucket className="cursor-pointer hover:text-blue-500" />
            <SiJirasoftware className="cursor-pointer hover:text-blue-300" />
          </div>
        </div>
        <Footer
          theme={theme}
          setTheme={setTheme}
          lang={lang}
          setLang={setLang}
        />
      </div>
    </>
  );
}
