import Head from "next/head";
import Image from "next/image";

import { Lexend } from "@next/font/google";
import Footer from "@/components/Footer";

// If loading a variable font, you don't need to specify the font weight
const lexend = Lexend({ subsets: ["latin"], weight: "800" });

type Props = {
	theme: boolean;
	setTheme: boolean | any;
};

export default function Home({ theme, setTheme }: Props) {
	return (
		<>
			<Head>
				<title>My Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<div
				className={`${
					theme
						? "w-full h-full flex flex-col justify-between overflow-auto bg-gradient-to-b from-white to-[#f1f7fd] rounded-md duration-200"
						: "w-full h-full flex flex-col justify-between overflow-auto bg-gradient-to-b from-[#17181a] to-transparent rounded-md duration-200"
				}`}>
				<div>
					<div className="relative w-full max-h-80 object-cover">
						{theme ? (
							<Image
								className="w-full max-h-80 object-cover"
								src="/ligth.jpg"
								alt="Banner"
								width={1000}
								height={1000}
								priority
								style={{ borderRadius: 5 }}
							/>
						) : (
							<Image
								className="w-full max-h-80 object-cover"
								src="/dark.png"
								alt="Banner"
								width={1000}
								height={1000}
								priority
								style={{ borderRadius: 5 }}
							/>
						)}
						<div
							className={`${
								theme
									? "flex flex-col gap-5 items-center justify-center absolute left-0 right-0 bottom-0 top-0  rounded-lg"
									: "flex flex-col gap-5 items-center justify-center absolute left-0 right-0 bottom-0 top-0  rounded-lg"
							}`}>
							<div className="text-7xl text-white font-extrabold">
								<h1 className={lexend.className}>WELCOME!</h1>
							</div>
							<p className="text-xl text-white font-extralight">
								To my Modern Portfolio!
							</p>
						</div>
					</div>

					<div className="w-full p-5 flex flex-col gap-5 pt-10">
						<h1 className="text-5xl font-bold">Hey, I'm Sebastian!</h1>
						<p className="text-xl font-light">
							Welcome to my Dashboard Modern Portfolio!. ❤️
						</p>
						<div className="relative">
							<span className="absolute w-full left-0 right-0 h-0.5 bg-white/5"></span>
							<span className="absolute w-full left-0 right-0 h-0.5 bg-black/5"></span>
						</div>
						<p className="text-xl pt-3 font-thin">
							I am a software developer in Colombia. I do open source projects
							and write about code, design and life. I like photography,
							drawing, science fiction, reading and games.
						</p>
					</div>
				</div>

				<Footer theme={theme} />
			</div>
		</>
	);
}
