import Head from "next/head";
import Footer from "@/components/Footer";
import { InterfaceThemeLanguage } from "@/interfaces/Interface";
import { Lexend } from "@next/font/google";
import Image from "next/image";
const lexend = Lexend({ subsets: ["latin"], weight: "800" });

export default function Home({
  theme,
  setTheme,
  lang,
}: InterfaceThemeLanguage) {
  return (
    <>
      <Head>
        <title>{lang ? "My Portfolio" : "Mi Portafolio"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div
        className={`${
          theme
            ? "w-full h-full flex flex-col justify-between overflow-auto bg-gradient-to-b from-[#f6f6f7] to-transparent rounded-md"
            : "w-full h-full flex flex-col justify-between overflow-auto bg-gradient-to-b from-[#17181a] to-transparent rounded-md"
        }`}
      >
        <div>
          <div className="relative w-full max-h-80">
            <div
              className={`${
                theme
                  ? "max-h-60 h-60 bg-gradient-to-b from-white to-transparent"
                  : "max-h-60 h-60 bg-gradient-to-b from-neutral-900 to-transparent"
              }`}
            ></div>
            <div
              className={`${
                theme
                  ? "flex flex-col gap-5 items-center justify-center absolute left-0 right-0 bottom-0 top-0  rounded-lg"
                  : "flex flex-col gap-5 items-center justify-center absolute left-0 right-0 bottom-0 top-0  rounded-lg"
              }`}
            >
              <div
                className={`${
                  theme
                    ? "relative animate-text text-7xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-black via-black/40 to-black"
                    : "relative animate-text text-7xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-white via-white/40 to-white"
                }`}
              >
                <div
                  className={`${
                    theme
                      ? "absolute bottom-10 -left-24 w-2 h-2 rounded-full bg-black animate-bubles blur-lg"
                      : "absolute bottom-10 -left-24 w-2 h-2 rounded-full bg-white animate-bubles blur-lg"
                  }`}
                ></div>

                <div
                  className={`${
                    theme
                      ? "absolute bottom-20 right-0 w-2 h-2 rounded-full bg-blue-500 animate-bubles2 blur-lg"
                      : "absolute bottom-20 right-0 w-2 h-2 rounded-full bg-blue-500 animate-bubles2 blur-lg"
                  }`}
                ></div>

                <div
                  className={`${
                    theme
                      ? "absolute bottom-28 left-10 w-5 h-5 rounded-full bg-yellow-500 animate-bubles3 blur-lg"
                      : "absolute bottom-28 left-10 w-5 h-5 rounded-full bg-yellow-500 animate-bubles3 blur-lg"
                  }`}
                ></div>

                <div
                  className={`${
                    theme
                      ? "absolute top-28 right-10 w-5 h-5 rounded-full bg-green-500 animate-bubles4 blur-lg"
                      : "absolute top-28 right-10 w-5 h-5 rounded-full bg-green-500 animate-bubles4 blur-lg"
                  }`}
                ></div>

                <h1 className={lexend.className}>
                  {lang ? "WELCOME!" : "BIENVENIDO!"}
                </h1>
              </div>
            </div>
          </div>

          <div className="w-full p-7 flex flex-col gap-5">
            <p className="font-mono 2xl:text-xl text-base">
              {lang ? "Hi, my name is" : "Hola, mi nombre es"}
            </p>
            <h1 className={`${lexend.className} 2xl:text-5xl text-5xl`}>
              Sebastian Giraldo.
            </h1>
            <h1 className={`${lexend.className} 2xl:text-5xl text-5xl`}>
              {lang
                ? "& I build things for the web.. ❤️"
                : "Y Construyo cosas para la web.. ❤️"}
            </h1>
            <p className="text-xl font-sans">
              {lang
                ? "As a skilled web developer with experience using React, I have a strong understanding of modern web development technologies and a proven track record of creating high-performing, visually-appealing websites and web applications.  With my experience in React, I am able to create responsive user interfaces and implement complex functionality with the help of component-based architecture. "
                : "Como desarrollador web experto con experiencia en el uso de React, tengo una sólida comprensión de las tecnologías de desarrollo web modernas y un historial probado de creación de sitios web y aplicaciones web de alto rendimiento y visualmente atractivos.  Con mi experiencia en React, soy capaz de crear interfaces de usuario responsivas e implementar funcionalidades complejas con la ayuda de la arquitectura basada en componentes. "}
              <br />
              <br />
              {lang
                ? "I'm a quick learner and work well under pressure, and I am excited about the opportunity to bring my skills and experience to a new role as a web developer."
                : "Aprendo rápido y trabajo bien bajo presión, y estoy entusiasmado con la oportunidad de aportar mis habilidades y experiencia a un nuevo rol como desarrollador web."}
            </p>
          </div>
        </div>

        <Footer
          theme={theme}
          setTheme={setTheme}
          lang={lang}
          setLang={setTheme}
        />
      </div>
    </>
  );
}
