import Header from '@/components/Header'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Modern Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/*Hero */}
      {/*About */}
      {/*Experience */}
      {/*Skills */}
      {/*Projects */}
      {/*Contact me */}
      {/*Footer */}
    </>
  )
}
