import { Lexend } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import Footer from "@/components/Footer";
import { InterfaceThemeLanguage } from "@/interfaces/Interface";
import { ProjectsData } from "@/utils/projects";

const lexend = Lexend({ subsets: ["latin"], weight: "800" });
import { FaGithub } from "react-icons/fa";
import { GoFileSubmodule } from "react-icons/go";
import { TfiUnlink } from "react-icons/tfi";

export default function About({
  theme,
  setTheme,
  lang,
  setLang,
}: InterfaceThemeLanguage) {
  return (
    <>
      <Head>
        <title>
          {lang ? "Projects - Portfolio" : "Proyectos - Portafolio"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div
        className={`${
          theme
            ? "w-full h-full flex flex-col justify-between overflow-auto bg-gradient-to-b from-white to-transparent rounded-md backdrop-blur-3xl"
            : "w-full h-full flex flex-col justify-between overflow-auto bg-transparent rounded-md backdrop-blur-3xl"
        }`}
      >
        <div>
          <div className="w-full py-5 px-3 flex flex-col  gap-5">
            <h1
              className={lexend.className}
              style={{ fontSize: 50, fontWeight: 800, lineHeight: 1 }}
            >
              {lang ? "Projects" : "Proyectos"}
            </h1>
            <p className="text-xl font-sans">
              {lang
                ? "A list of projects I have been working on or built"
                : "Una lista de proyectos en los que he estado trabajando o que he construido"}
            </p>
          </div>

          <div className="w-full py-5 pl-3 pr-5 pt-0 grid grid-cols-1 gap-4">
            {ProjectsData.map(
              ({ id, title, example, repo, live, techs, animation }) => (
                <div
                  key={id}
                  className={`relative w-full rounded-md flex flex-col justify-between gap-5 ${
                    theme ? "bg-[#11101004]" : "bg-[#1110103b]"
                  }`}
                >
                  <div className="flex justify-between items-center z-20 px-3 pt-3">
                    <GoFileSubmodule className=" text-3xl" />
                    <a href={repo} rel="noreferrer" target="_blank">
                      <FaGithub className=" text-2xl" />
                    </a>
                  </div>
                  <div className="flex flex-col justify-between gap-5">
                    <div className="w-full flex flex-col px-3">
                      <h1 className="text-3xl font-semibold">{title}</h1>
                    </div>
                    <div className="w-full px-3">
                      <a href={live} rel="noreferrer" target="_blank">
                        <Image
                          className="rounded-md"
                          src={example}
                          width={2000}
                          height={2000}
                          priority
                          alt={title}
                        />
                      </a>
                    </div>
                  </div>

                  <div className="flex justify-between items-center px-3 pb-3">
                    <p className="font-semibold flex gap-3">{techs}</p>
                    <div className="flex gap-2 items-center">
                      <a href={live} rel="noreferrer" target="_blank">
                        {live ? (
                          <p className="flex items-center gap-3 font-bold">
                            live <TfiUnlink />
                          </p>
                        ) : (
                          ""
                        )}
                      </a>
                    </div>
                  </div>
                </div>
              )
            )}
          </div>
        </div>

        <Footer
          theme={theme}
          setTheme={setTheme}
          lang={lang}
          setLang={setLang}
        />
      </div>
    </>
  );
}
